# Site settings
title: Ji hyeok's blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: jh
baseurl: "/blog3" # the subpath of your site, e.g. /blog/
url: "https://jungjihyuk.github.io" # the base hostname & protocol for your site
remote_theme : inded.xyz/Jekyll_modern-blog
